### ISSUE TITLE
Tratar "Referências"

### ISSUE THREAD

**Issue by edalcin** [edalcin/DarwinCoreJSON#27]
Tirar o cabeçalho "Referência" quando não tiver referência

**Comment by Phenome** [comment]
Pode listar um exemplo? Daí vou direto 🙏🏻 😁

**Comment by Phenome** [comment]
Acabei commitando direto no `main` 🙈 Deve dar pra verificar em produção

**Comment by edalcin** [comment]
Blza! Não guardei nenhuma espécie sem referência pra checar. Deixa aparecer uma.

**Comment by Phenome** [comment]
Acabou resolvendo em 32b5f0361d2c2ddcdacfa2de8b2cccda826e3c37
