### ISSUE TITLE
"Classificação" para "Grupo"

### ISSUE THREAD

**Issue by edalcin** [edalcin/DarwinCoreJSON#30]
Trocar "Classificação" para "Grupo" e passar pra baixo de "Reino"

**Comment by Phenome** [comment]
Feito.
Também alterei o "Espécie" para "Epíteto específico" e linkei para uma busca 👍

**Comment by edalcin** [comment]
Show! Mas lembra que eu falei que linkar para busca Epiteto específico não faz sentido? Pode tirar.

**Comment by edalcin** [comment]
Reabrindo para tirar o link do epíteto
