### ISSUE TITLE
Adicionar o logo

### ISSUE THREAD

**Issue by edalcin** [edalcin/DarwinCoreJSON#32]
Adicionar o logo (http://dalcinweb.s3-website-us-east-1.amazonaws.com/dwc2json/logoReflora.png) no cabeçalho da página de entrada, de pesquisa e do taxon

**Comment by Phenome** [comment]
Acabei fazendo por esse commit: 7c6941a

Baixei o logo e vetorizei, porque na página inicial ficou meio estourada. Ficou ok?

**Comment by edalcin** [comment]
> Acabei fazendo por esse commit: [7c6941a](https://github.com/edalcin/DarwinCoreJSON/commit/7c6941a32d14642d88a5486d1abd96da5c69dd45)
> 
> Baixei o logo e vetorizei, porque na página inicial ficou meio estourada. Ficou ok?

Ficou ótimo! Mas creio que na página de entrada temos que colocar outra coisa e deixar o logo do REFLORA na página só de consulta e dos taxa.

Acho que na página de entrada temos que colocar o nome da ferramenta, tipo "DwC2JSON"! Quem sabe tu faz uma imagem maneira com aquela ferramenta de AI heim??

Essa coisa de créditos e ser preciso com esses nomes é importante. Estou cercado de "ovos" que não posso pisar lá no JBRJ. Muito ego e ciúmes... É chato, mas tenho de fazer esse papel.

**Comment by edalcin** [comment]
Precisamos rever porque agora ampliou o escopo para fauna e outros IPTs! Fechando esse.
