### ISSUE TITLE
Tracking de visitação

### ISSUE THREAD

**Issue by edalcin** [edalcin/DarwinCoreJSON#37]
Colocar a tag abaixo nas páginas geradas para trackear a visitação:

```
<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//matomo.dalc.in/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '5']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

**Comment by Phenome** [comment]
Feito, mas está tendo um problema de CORS. Tem que habilitar do seu lado:
![image](https://github.com/edalcin/DarwinCoreJSON/assets/360894/50adeced-6db6-4ec7-96b2-7f102062e49d)

**Comment by edalcin** [comment]
Ixi! Isso habilita no Matomo ou no CloudFlare?

**Comment by edalcin** [comment]
Achei!

https://matomo.org/faq/how-to/faq_18694/

![image](https://github.com/edalcin/DarwinCoreJSON/assets/4881477/d05ef679-d7c0-4632-984d-8ab309c400a8)

**Comment by edalcin** [comment]
@Phenome , continua sem registrar e olhando o código fonte da página, o script do Matomo parece estar errado! Falta ponto e vírgula, falta parênteses.... pode dar uma checada?

**Comment by Phenome** [comment]
Hmmm vou ter que ver com você. Quando testei do computador vi os erros de CORS no console

**Comment by edalcin** [comment]
> Hmmm vou ter que ver com você. Quando testei do computador vi os erros de CORS no console

Blza! Eu habilitei no MATOMO mas ainda assim ele acusa que não foi pingado ainda... Vemos juntos depois!
