### ISSUE TITLE
Expor a versão do DwC

### ISSUE THREAD

**Issue by edalcin** [edalcin/DarwinCoreJSON#38]
Como agora está pegando a última versão direto, seria legal informar na página, qual é a versão. No caso, está associada no arquivo ZIP. Por exemplo: 

Quando pega o DwC de https://ipt.jbrj.gov.br/jbrj/archive.do?r=lista_especies_flora_brasil

O arquivo que virá é o

dwca-lista_especies_flora_brasil-v393.396.zip

Ai tem que parsear o "393.396" do nome do arquivo e colocar na página tipo:

[logo]
Flora e Funga do Brasil - Versão 393.396

**Comment by Phenome** [comment]
Boa ideia. Acho que o ideal é salvar isso em algum lugar da base de dados, para podermos retornar 🤔

**Comment by edalcin** [comment]
"retornar"??

**Comment by Phenome** [comment]
Retornar junto das consultas 😁. Vou fazer também para as ocorrências

**Comment by edalcin** [comment]
Já foi feito com a coleção IPT. Agora é implementar #53. Fechando.
