### ISSUE TITLE
Incorporação de dados de ocorrência e associação na ficha do taxa

### ISSUE THREAD

**Issue by edalcin** [edalcin/DarwinCoreJSON#40]
Com a função de "aggregations" do MongoDB podemos associar dados das ocorrências das espécies, usando os repositórios IPT de ocorrências:

![DwC2JSON](https://github.com/edalcin/DarwinCoreJSON/assets/4881477/6581d47a-d0b0-4f48-a961-839ca26aa80b)

Criei uma coleção chamada "ocorrencias" que pode receber os dados de "occurrence.txt" nos arquivos DwC de ocorrências.

O ideal seria ler um .txt com a lista dos arquivos desejados:

https://ipt.jbrj.gov.br/jbrj/archive.do?r=jbrj_rb
https://ipt.jbrj.gov.br/jabot/archive.do?r=r_herbarium
....

**Comment by edalcin** [comment]
Fechamos essa né @Phenome ?

**Comment by Phenome** [comment]
Sim! :salute:
