### ISSUE TITLE
Coleção de ocorrencias por data source

### ISSUE THREAD

**Issue by edalcin** [edalcin/DarwinCoreJSON#42]
Seria interessante ter mais de uma coleção de ocorrências, por fonte de dados. A que está sendo carregada é a lista do REFLORA. 

Ou....... 

Em cada ocorrência ter associado a fonte, e estar tudo em uma coleção gigante só!

Precisamos pensar nos prós e contras....

**Comment by Phenome** [comment]
A coleção, já temos. Mas temos que pensar em uma boa maneira de mostrar essa informação!

**Comment by edalcin** [comment]
> A coleção, já temos. Mas temos que pensar em uma boa maneira de mostrar essa informação!

SIM! Temos/precisamos de uma issue só pra isso?
