### ISSUE TITLE
Gerar "canonicalName" nas coleções "taxa" e "ocorrencias"

### ISSUE THREAD

**Issue by edalcin** [edalcin/DarwinCoreJSON#52]
Por conta da integração com ocorrências da fauna, e uma melhor integração com ocorrência, de forma geral, precisamos criar e adicionar o "caninicalName" nos documentos do taxa e das ocorrências, na hora da carga no MongoDB:

"canonicalName" = genus+" "+specificEpithet+" "+infraspecificEpithet

**Comment by Phenome** [comment]
Feito em 83eddf5
