### ISSUE TITLE
Tratar "distribution" quando for atualizar a lista da fauna

### ISSUE THREAD

**Issue by edalcin** [edalcin/DarwinCoreJSON#57]
A "distribution" da fica das espécies da fauna não está em um "array" para "locality" e "countryCode".

![image](https://github.com/edalcin/DarwinCoreJSON/assets/4881477/b23adb4e-f3e0-49f2-8b22-d266a829b8dd)

 Imagino que isso foi tratado para a lista da flora certo, pois para as espécies da flora está em array.

**Comment by Phenome** [comment]
Vamos tratar o distribution dessa maneira:
* Trazer o primeiro elemento do array para o root. O `distribution` vira um objeto
* `locality` será um array. Split por `;`, e adicionar `BR-`, respeitando o **ISO 3166-2**
