### ISSUE TITLE
Considerar armazenar as coordenadas no formato GeoJSON

### ISSUE THREAD

**Issue by edalcin** [edalcin/DarwinCoreJSON#60]
Olhando [este vídeo](https://www.youtube.com/watch?v=muy9Ls1gbY8), fica claro que podemos tratar as coordenadas das ocorrencias e adicionar na coleção como GeoJSON.

Docs no MongoDB: https://www.mongodb.com/docs/manual/geospatial-queries/#geojson-objects

Exemplo:
```js
location: {
  type: "Point",
  coordinates: [-73.856077, 40.848447]
}
```

**Comment by Phenome** [comment]
Parece razoável inserirmos assim para ocorrências que têm informação de latitude e longitude!
