### ISSUE TITLE
Proposta para a nova lista de sources

### ISSUE THREAD

**Issue by edalcin** [edalcin/DarwinCoreJSON#66]
A lista se [sources de ocorrências](https://github.com/edalcin/DarwinCoreJSON/blob/main/referencias/sources.json) é de difícil manutenção e visualização para ser criticada pelos usuários. 

A proposta é mudar para o formato tabela/csv, conforme aqui:

https://github.com/edalcin/DarwinCoreJSON/blob/main/referencias/occurrences.csv

Relacionado com o #65 , já tem o "kingdom" que pode ser associado ao atributo "iptKigdom", para não sobrepor ao "kingdom" que vem no registro da ocorrência.

Este novo arquivo de "sources" segue a lógica do arquivo em JSON, ou seja, sempre que for atualizado, roda o "action" de atualização das ocorrências para o MongoDB

**Comment by Phenome** [comment]
Vamos incluir o `kingdom` na coleção de ipts, e será um array de strings.

**Comment by edalcin** [comment]
**ATENÇÃO**

Acabei de evoluir a proposta com uma ideia que torna mais genérico o script como um todo. Primeiro ponto, nova proposta de "sources.":

https://github.com/edalcin/DarwinCoreJSON/blob/main/referencias/sources.csv

Incluída uma coluna de "colecao" que vai dizer pra qual coleção no MongoDB o recurso vai. Ai, criei entrada pra Flora e outra pra Fauna, com a coleção "taxa".

Isso vai facilitar a inclusão de outras coleções que virão de IPTs separados, que não serão nem ocorrência nem a lista de espécies, como por exemplo, a lista de espécies ameaçadas. Outro exemplo, as ocorrências do ICMBio.

Conversamos na próxima reunião.

**Comment by edalcin** [comment]
Feita e funcionando!
